FROM 	wordpress:5.2.4-php7.2-apache

RUN docker-php-ext-install apc
RUN docker-php-ext-install apcu
RUN docker-php-ext-install bz2
RUN docker-php-ext-install calendar
RUN docker-php-ext-install Core
RUN docker-php-ext-install ctype
RUN docker-php-ext-install curl
RUN docker-php-ext-install date
RUN docker-php-ext-install dom
RUN docker-php-ext-install exif
RUN docker-php-ext-install fileinfo
RUN docker-php-ext-install filter
RUN docker-php-ext-install ftp
RUN docker-php-ext-install gd
RUN docker-php-ext-install gettext
RUN docker-php-ext-install gmp
RUN docker-php-ext-install hash
RUN docker-php-ext-install iconv
RUN docker-php-ext-install igbinary
RUN docker-php-ext-install json
RUN docker-php-ext-install libxml
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install memcache
RUN docker-php-ext-install memcached
RUN docker-php-ext-install msgpack
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install mysqlnd
RUN docker-php-ext-install openssl
RUN docker-php-ext-install pcntl
RUN docker-php-ext-install pcre
RUN docker-php-ext-install PDO
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install Phar
RUN docker-php-ext-install posix
RUN docker-php-ext-install pspell
RUN docker-php-ext-install readline
RUN docker-php-ext-install recode
RUN docker-php-ext-install redis
RUN docker-php-ext-install Reflection
RUN docker-php-ext-install session
RUN docker-php-ext-install shmop
RUN docker-php-ext-install SimpleXML
RUN docker-php-ext-install soap
RUN docker-php-ext-install sockets
RUN docker-php-ext-install sodium
RUN docker-php-ext-install SPL
RUN docker-php-ext-install ssh2
RUN docker-php-ext-install standard
RUN docker-php-ext-install sysvmsg
RUN docker-php-ext-install sysvsem
RUN docker-php-ext-install sysvshm
RUN docker-php-ext-install tidy
RUN docker-php-ext-install tokenizer
RUN docker-php-ext-install wddx
RUN docker-php-ext-install xml
RUN docker-php-ext-install xmlreader
RUN docker-php-ext-install xmlrpc
RUN docker-php-ext-install xmlwriter
RUN docker-php-ext-install xsl
RUN docker-php-ext-install zip
RUN docker-php-ext-install zlib
